// generated by Fast Light User Interface Designer (fluid) version 1.0303
// subject to further manual editing.

#pragma once

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Int_Input.H>
#include <string>

#include <iostream>

class paramSelect {
	bool use_GPU;
	bool use_verbose;
	float slopeWeight;
	float roughWeight;
	float shadowWeight;
	int numSites;
public:
	paramSelect();
	Fl_Double_Window *param_window;
public:
	Fl_Button *bt_default;
private:
	inline void cb_bt_default_i(Fl_Button*, void*);
	static void cb_bt_default(Fl_Button*, void*);
public:
	Fl_Group *gpu_radio_group;
	Fl_Round_Button *radio_CPU;
	Fl_Round_Button *radio_GPU;
	Fl_Button *bt_launch;
private:
	inline void cb_bt_launch_i(Fl_Button*, void*);
	static void cb_bt_launch(Fl_Button*, void*);
public:
	Fl_Check_Button *check_verbose;
	Fl_Value_Input *in_slope;
	Fl_Value_Input *in_rough;
	Fl_Value_Input *in_shadow;
	Fl_Int_Input *in_sites;

	void show();
	void print_params();
	void getParams(bool&, bool&, float&, float&, float&, int&);
	void validate();
	
};
